DROP DATABASE IF EXISTS upnext;
CREATE DATABASE upnext;
USE upnext;

-- TABEL USERS
CREATE TABLE users (
    id_user INT AUTO_INCREMENT PRIMARY KEY,
    nama_lengkap VARCHAR(100) DEFAULT NULL,
    nama_pengguna VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    no_telp VARCHAR(20) DEFAULT NULL,
    kata_sandi VARCHAR(255) NOT NULL,
    photo VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- TABEL EVENTS
CREATE TABLE events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    judul VARCHAR(200) NOT NULL,
    kategori VARCHAR(100) NOT NULL,
    poster VARCHAR(255),
    deskripsi TEXT NOT NULL,
    benefit TEXT,
    register_link VARCHAR(255),
    detail_link VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL BOOKMARKS
CREATE TABLE bookmarks (
    id_bookmark INT AUTO_INCREMENT PRIMARY KEY,
    id_user INT,
    id_event INT,
    FOREIGN KEY (id_user) REFERENCES users(id_user) ON DELETE CASCADE,
    FOREIGN KEY (id_event) REFERENCES events(id)
);
